export const events = [
  {
    id: "1",
    start: "2022-09-30",
    end: "",
    title: " @井手",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  /** 2022/10 */
  {
    id: "2",
    start: "2022-10-01",
    end: "",
    title: " @井手",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "3",
    start: "2022-10-07",
    end: "",
    title: " @井手",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "4",
    start: "2022-10-08",
    end: "",
    title: "お休み",
    description: "",
    backgroundColor: "red",
    borderColor: "red",
    editable: false,
  },
  {
    id: "5",
    start: "2022-10-14",
    end: "",
    title: " @井手",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "6",
    start: "2022-10-15",
    end: "",
    title: " @井手",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "7",
    start: "2022-10-21",
    end: "",
    title: " @井手",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "8",
    start: "2022-10-22",
    end: "",
    title: " @井手",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "9",
    start: "2022-10-28",
    end: "",
    title: " @井手",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "9",
    start: "2022-10-29",
    end: "",
    title: "HackBAR.LT 15:00 ~ 18:00",
    description: "",
    backgroundColor: "orange",
    borderColor: "orange",
    editable: true,
  },
  {
    id: "10",
    start: "2022-10-29",
    end: "",
    title: " @井手",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: true,
  },
  /** 2022/11 */
  {
    id: "11",
    start: "2022-11-04",
    end: "",
    title: "お休み",
    description: "",
    backgroundColor: "red",
    borderColor: "red",
    editable: false,
  },
  {
    id: "12",
    start: "2022-11-05",
    end: "",
    title: "お休み",
    description: "",
    backgroundColor: "red",
    borderColor: "red",
    editable: false,
  },
  {
    id: "13",
    start: "2022-11-11",
    end: "",
    title: " @井手",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "14",
    start: "2022-11-12",
    end: "",
    title: " @井手",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "15",
    start: "2022-11-18",
    end: "",
    title: "お休み",
    description: "",
    backgroundColor: "red",
    borderColor: "red",
    editable: false,
  },
  {
    id: "16",
    start: "2022-11-18",
    end: "",
    title: "※Hack.BAR鳥取 ",
    description: "",
    backgroundColor: "orange",
    borderColor: "orange",
    editable: true,
  },
  {
    id: "17",
    start: "2022-11-19",
    end: "",
    title: " @井手",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "18",
    start: "2022-11-25",
    end: "",
    title: " @井手",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "19",
    start: "2022-11-26",
    end: "",
    title: " @井手",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  /** 2022/12 */
  {
    id: "20",
    start: "2022-12-02",
    end: "",
    title: " @masashi_navi",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "21",
    start: "2022-12-03",
    end: "",
    title: " @shouhi_ide",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "22",
    start: "2022-12-09",
    end: "",
    title: " @masashi_navi",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "23",
    start: "2022-12-10",
    end: "",
    title: " @shouhi_ide",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "24",
    start: "2022-12-16",
    end: "",
    title: " @masashi_navi",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "25",
    start: "2022-12-16",
    end: "",
    title: "w/神戸エンジニアラボ Event",
    description: "",
    backgroundColor: "orange",
    borderColor: "orange",
    editable: false,
  },
  {
    id: "26",
    start: "2022-12-17",
    end: "",
    title: " @shouhi_ide",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "27",
    start: "2022-12-23",
    end: "",
    title: " @masashi_navi",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "28",
    start: "2022-12-24",
    end: "",
    title: " @shouhi_ide",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "29",
    start: "2022-12-24",
    end: "",
    title: "Xmas EVENT 🎅🎄",
    description: "",
    backgroundColor: "orange",
    borderColor: "orange",
    editable: true,
  },
  {
    id: "30",
    start: "2022-12-30",
    end: "",
    title: "お休み",
    description: "",
    backgroundColor: "red",
    borderColor: "red",
    editable: true,
  },
  {
    id: "31",
    start: "2022-12-31",
    end: "",
    title: "お休み",
    description: "",
    backgroundColor: "red",
    borderColor: "red",
    editable: false,
  },
  /** 2023/1 */
  {
    id: "32",
    start: "2023-01-06",
    end: "",
    title: " @masashi_navi",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "33",
    start: "2023-01-07",
    end: "",
    title: " @shouhi_ide",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "34",
    start: "2023-01-13",
    end: "",
    title: " @masashi_navi",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "35",
    start: "2023-01-14",
    end: "",
    title: " @shouhi_ide",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "36",
    start: "2023-01-20",
    end: "",
    title: " @masashi_navi",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "37",
    start: "2023-01-21",
    end: "",
    title: " @shouhi_ide",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "38",
    start: "2023-01-23",
    end: "",
    title: "漫画村創始者：星野ロミ対談イベント！！",
    description: "",
    backgroundColor: "orange",
    borderColor: "orange",
    editable: false,
  },
  {
    id: "39",
    start: "2023-01-27",
    end: "",
    title: " @masashi_navi",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "40",
    start: "2023-01-28",
    end: "",
    title: "アルゴリズム勉強会",
    description: "",
    backgroundColor: "orange",
    borderColor: "orange",
    editable: false,
  },
  {
    id: "41",
    start: "2023-01-28",
    end: "",
    title: " @shouhi_ide",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  /** 2023/2 */
  {
    id: "42",
    start: "2023-02-03",
    end: "",
    title: " @masashi_navi",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "43",
    start: "2023-02-04",
    end: "",
    title: "@shouhi_ide",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "44",
    start: "2023-02-04",
    end: "",
    title: "21:00~ AtCoder Contest",
    description: "",
    backgroundColor: "blue",
    borderColor: "blue",
    editable: false,
  },
  {
    id: "45",
    start: "2023-02-10",
    end: "",
    title: " @masashi_navi",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "46",
    start: "2023-02-11",
    end: "",
    title: "お休み",
    description: "",
    backgroundColor: "red",
    borderColor: "red",
    editable: false,
  },
  {
    id: "47",
    start: "2023-02-17",
    end: "",
    title: " @masashi_navi",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "48",
    start: "2023-02-18",
    end: "",
    title: " @shouhi_ide",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "49",
    start: "2023-02-18",
    end: "",
    title: "21:00~ AtCoder Contest",
    description: "",
    backgroundColor: "blue",
    borderColor: "blue",
    editable: false,
  },
  {
    id: "50",
    start: "2023-02-24",
    end: "",
    title: " @masashi_navi",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "51",
    start: "2023-02-25",
    end: "",
    title: " @shouhi_ide",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "52",
    start: "2023-02-25",
    end: "",
    title: "21:00~ AtCoder Contest",
    description: "",
    backgroundColor: "blue",
    borderColor: "blue",
    editable: false,
  },
  /** 2023/3 */
  {
    id: "53",
    start: "2023-03-03",
    end: "",
    title: "18:00~ @masashi_navi",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "54",
    start: "2023-03-04",
    end: "",
    title: "13:00~ ごくごく会 w/三宮.dev",
    description: "",
    backgroundColor: "orange",
    borderColor: "orange",
    editable: false,
  },
  {
    id: "55",
    start: "2023-03-04",
    end: "",
    title: "21:00~ AtCoder Contest",
    description: "",
    backgroundColor: "blue",
    borderColor: "blue",
    editable: false,
  },
  {
    id: "56",
    start: "2023-03-10",
    end: "",
    title: "18:00~ Hack.BAR 福岡",
    description: "",
    backgroundColor: "orange",
    borderColor: "orange",
    editable: false,
  },
  {
    id: "57",
    start: "2023-03-10",
    end: "",
    title: "18:00~ @masashi_navi",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "58",
    start: "2023-03-11",
    end: "",
    title: "18:00~ @shouhi_ide",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "59",
    start: "2023-03-11",
    end: "",
    title: "21:00~ AtCoder Contest",
    description: "",
    backgroundColor: "blue",
    borderColor: "blue",
    editable: false,
  },
  {
    id: "60",
    start: "2023-03-17",
    end: "",
    title: "18:00~ @masashi_navi",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "61",
    start: "2023-03-18",
    end: "",
    title: "お休み",
    description: "",
    backgroundColor: "red",
    borderColor: "red",
    editable: false,
  },
  {
    id: "62",
    start: "2023-03-24",
    end: "",
    title: "18:00~ @masashi_navi",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "63",
    start: "2023-03-25",
    end: "",
    title: "18:00~ @shouhi_ide",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "64",
    start: "2023-03-25",
    end: "",
    title: "21:00~ AtCoder Contest",
    description: "",
    backgroundColor: "blue",
    borderColor: "blue",
    editable: false,
  },
  {
    id: "65",
    start: "2023-03-31",
    end: "",
    title: "18:00~ @masashi_navi",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
  {
    id: "66",
    start: "2023-03-04",
    end: "",
    title: "18:00~@shouhi_ide",
    description: "",
    backgroundColor: "grey",
    borderColor: "grey",
    editable: false,
  },
];
