export const events = [
  { id: '1',
    start: '2022-09-30',
    end: '',
    title: 'Open @井手',
    description: '',
    backgroundColor: 'grey',
    borderColor: 'grey',
    editable: false,
  },
  { id: '2',
    start: '2022-10-01',
    end: '',
    title: 'Open @井手',
    description: '',
    backgroundColor: 'grey',
    borderColor: 'grey',
    editable: false,
  },
  { id: '3',
    start: '2022-10-07',
    end: '',
    title: 'Open @井手',
    description: '',
    backgroundColor: 'grey',
    borderColor: 'grey',
    editable: false,
  },
  { id: '4',
    start: '2022-10-08',
    end: '',
    title: 'お休み',
    description: '',
    backgroundColor: 'red',
    borderColor: 'red',
    editable: false,
  },
  { id: '5',
    start: '2022-10-14',
    end: '',
    title: 'Open @井手',
    description: '',
    backgroundColor: 'grey',
    borderColor: 'grey',
    editable: false,
  },
  { id: '6',
    start: '2022-10-15',
    end: '',
    title: 'Open @井手',
    description: '',
    backgroundColor: 'grey',
    borderColor: 'grey',
    editable: false,
  },
  { id: '7',
    start: '2022-10-21',
    end: '',
    title: 'Open @井手',
    description: '',
    backgroundColor: 'grey',
    borderColor: 'grey',
    editable: false,
  },
  { id: '8',
    start: '2022-10-22',
    end: '',
    title: 'Open @井手',
    description: '',
    backgroundColor: 'grey',
    borderColor: 'grey',
    editable: false,
  },
  { id: '9',
    start: '2022-10-28',
    end: '',
    title: 'Open @井手',
    description: '',
    backgroundColor: 'grey',
    borderColor: 'grey',
    editable: false,
  },
  { id: '9',
    start: '2022-10-29',
    end: '',
    title: 'HackBAR.LT 15:00 ~ 18:00',
    description: '',
    backgroundColor: 'orange',
    borderColor: 'orange',
    editable: true,
  },
  { id: '10',
    start: '2022-10-29',
    end: '',
    title: 'Open @井手',
    description: '',
    backgroundColor: 'grey',
    borderColor: 'grey',
    editable: true,
  },
];
